
server:
  port: 9999
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:mysql:///java_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    default-property-inclusion: non_null

logging:
  level:
    com.konglingzhan.manager.dao: debug

mbbatis:
  type-aliases-package: com.konglingzhan.manager.dao