
server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql:///java_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level: debugger

mbbatis:
  type-aliases-package: com.konglingzhan.manager.dao